### ISSUE TITLE
Using zerobrane as idle for 

### ISSUE THREAD

**Issue by PromGames** [pvaiko/course-generator#32]
@pvajko What Idle are you using for Lua?  Just Lua??

I was thinking to try zerobrane because it has love2d embebed and maybe it will work.

Did you try it?

I was looking at it and looks promiing:

`Configuration via command line
In addition to system-wide and per-user configurations, it is also possible to provide a set of parameters that will be in effect only for one session. Command line configuration can be specified by adding -cfg <filename> parameter when the application is started. For example, on Windows the command zbstudio.exe -cfg myconfig.lua will apply settings from myconfig.lua.

Individual commands can also be specified as configuration parameters; for example, zbstudio.exe -cfg "language='en'" will set Russian as the user interface language in the IDE. The format of the arguments passed using the command line is exactly the same as specified in the configuration files. If you need to set several values you can separate them with a semicolon: zbstudio.exe -cfg "language='en'; editor.fontsize = 12".`

Configuration file commands
The configuration files allow for several special commands:

include "file.lua": includes another (configuration) file using relative or absolute name. The relative name is checked against the directory (1) of the current configuration file, (2) of the per-user configuration file, and (3) of the system-wide configuration file (in that order). As soon as the file is found, it’s processed and the search is stopped.

package {}, package "path/", and package "file.lua": loads and processes the file as the package in the IDE. The first syntax (package {}) allows to include the package code in the config file, where the table passed is the package code. The other two load all files from a folder as packages or one particular package. Path and file names may be relative or absolute. The relative name is checked against . (current directory), packages/, and ../packages/ directories (in this order and all relative to the directory of the current configuration file). As soon as the file is found, it’s processed and the search is stopped.

Configuration variables
There are some rare cases in which you may need to access or change some values that are not configuration settings in the IDE. For example, you may need access the spec configuration (ide.specs.lua) or call lua functions from an inline package (package { onRegister = function() table.insert(something, 'else') end }). Before version 1.21, local G = ... was used to provide access to the global environment from the config file. Starting from version 1.21, this is no longer needed, as the global environment is already available, so those methods can be used directly (as can be seen in cfg/user-sample.lua). The access and the processing is the same for all config files.

**Comment by pvajko** [comment]
I tried, but did not like it. I'm using IntelliJ Idea with the EmmyLua plugin. Also for Courseplay.

**Comment by PromGames** [comment]
I have installed it and works nice for debugging. I was looking for something just to show the love2d screen I have found some library in c# that could be valid for love2d, I also have the pda_map in png format if you want to add to the love2d the image of the pda normally 2048 x2048 and get the draw on top of the png
