### ISSUE TITLE
Course generation/Fieldwork mode missing.  Version 6.01.00196.dev

### ISSUE THREAD

**Issue by Shiftry** [pvaiko/course-generator#34]
I just updated courseplay to the current version "6.01.00196.dev" from github link https://github.com/courseplay/courseplay

I can use all me already generated courses but when i select fieldwork or any other mode appropriate for the tool i am working with i am getting the mode specific settings option available (snake up/down arrow) but when i enter it i am not getting the 2 buttons that will allow me to generate courses.  Instead i am getting settings for. 
Lane offset
Symmetric lane change
Turn on field
Pathfinding
Tool offset horizontal
Tool offset vertical
Opposite turn direction

Another issue i noticed is that no mather what tool i use Fert/seeding mode is available but Fieldwork mode is grayed out on all tools.  I hope this info is helpful and can be resolved
![fsScreen_2019_04_22_18_58_35](https://user-images.githubusercontent.com/46154900/56512860-e5380480-6530-11e9-8ab8-60d7932f566e.png)
![fsScreen_2019_04_22_18_59_57](https://user-images.githubusercontent.com/46154900/56512861-e5380480-6530-11e9-9491-2c41c2cf157b.png)

**Comment by pvaiko** [comment]
First of all, this is the wrong repository to report problems with Courseplay, you want to go to https://github.com/Courseplay/courseplay/issues

Also, as you can see yourself on your second screenshot, there's a 'Course generation...' item you have to click to generate courses.
